import { Box } from "@chakra-ui/react";
import { Metadata } from "next";
import Image from "next/image";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <Box bg="secondary">
      Afdeling kwaliteit
    </Box>
  );
}

